### PR TITLE
General Fixes

### LINKED ISSUE #50: General improvements
- [x] align headline style for "highlighted x". It should be h6 instead of h4 (see [guidelines](https://www.figma.com/file/Xt5olSXad7hs5bQP9FF8Pl/DevX?node-id=1%3A482))
Bildschirmfoto 2022-09-05 um 08 28 36

- [x] update profile images for founding members

- [x] text in labels should be bold 
Bildschirmfoto 2022-09-05 um 08 55 07

- [x] update "highlighted cards" for dark theme -> labels should be white (see [mockup](https://www.figma.com/file/Xt5olSXad7hs5bQP9FF8Pl/DevX?node-id=366%3A398))
Bildschirmfoto 2022-09-05 um 08 53 42

- [x] adjust spacing and icon size for this components (see mockup)
Bildschirmfoto 2022-09-05 um 09 01 03

- [x] the big dots are still missing
Bildschirmfoto 2022-09-05 um 09 42 43

### PR DESCRIPTION
**Pull request by Cahllagerfeld**
closes partially #50

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/devx-community/pull/65"></a>

<a href="https://gitpod.io/#https://github.com/gitpod-io/devx-community/pull/65"></a>

### CODE REVIEW

File: src/lib/components/index/fragments/devx-pod.svelte [hunk 1]
```diff
@@ -3,9 +3,11 @@
 	import GradientContentCard from '../../library/gradient-content-card.svelte';
 	import { devXPod } from '$lib/contents/index/devx-content';
 	import Listen from '../../svgs/listen.svelte';
+	import Dot from '../../library/dot.svelte';
 </script>
 
-<ContentSection id="devx-pod" title="DevX Pod" annotation="listen" icon={Listen}>
+<ContentSection class="relative" id="devx-pod" title="DevX Pod" annotation="listen" icon={Listen}>
+	<Dot class="absolute block h-[650px] w-[650px] -translate-y-24 translate-x-[110%]" />
```
Comment (Cahllagerfeld) [inline src/lib/components/index/fragments/devx-pod.svelte]: Hey @nisarhassan12 I've added the big dots, two things need to be fixed though: 
1. The overflow should be hidden I guess
2. It causes issues on mobile devices and responsivness

Do you know a fix for them?

**Review by Cahllagerfeld — COMMENTED** [review]
In the worst case I can revert the last commit and we do the big dots in a follo wup
